"""Descripción de la migración

Revision ID: 34975162bd07
Revises: 
Create Date: 2024-11-22 11:05:45.031224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34975162bd07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('detail_order', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('detail_order', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('detail_order', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('detail_order', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('order', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('order', 'total',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('product', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.alter_column('product', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('product', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('order', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order', 'total',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_column('order', 'created_at')
    op.alter_column('detail_order', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('detail_order', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('detail_order', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('detail_order', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
