"""Descripción de los cambios

Revision ID: 35f8d6cd626b
Revises: 81661d7b4af6
Create Date: 2024-12-06 00:02:44.921025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f8d6cd626b'
down_revision: Union[str, None] = '81661d7b4af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
