"""Descripción de los cambios

Revision ID: 81661d7b4af6
Revises: 34975162bd07
Create Date: 2024-12-05 23:50:49.962025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81661d7b4af6'
down_revision: Union[str, None] = '34975162bd07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
