"""Descripción de los cambios

Revision ID: c30f9ee2f89a
Revises: 35f8d6cd626b
Create Date: 2024-12-06 00:36:15.059495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30f9ee2f89a'
down_revision: Union[str, None] = '35f8d6cd626b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
